server:
  port: 8091
spring:
  # 配置mysql数据源
#  datasource:
#    druid:
#      username: root
#      password: root
#      url: jdbc:mysql://8.130.15.99:3306/stock_db?useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true&useSSL=false&serverTimezone=Asia/Shanghai
#      driver-class-name: com.mysql.jdbc.Driver
#      # 初始化时建立物理连接的个数。初始化发生在显示调用 init 方法，或者第一次 getConnection 时
#      initialSize: 6
#      # 最小连接池数量
#      minIdle: 2
#      # 最大连接池数量
#      maxActive: 20
#      # 获取连接时最大等待时间，单位毫秒。配置了 maxWait 之后，缺省启用公平锁，
#      # 并发效率会有所下降，如果需要可以通过配置 useUnfairLock 属性为 true 使用非公平锁。
#      maxWait: 60000
  profiles:
    active: cache,stock,mq,sharding # 激活其它配置文件，如果存在多个文件，以逗号进行间隔即可
  main:
    allow-bean-definition-overriding: true # 配置允许容器中的bean资源被覆盖
# mybatis配置
mybatis:
  mapper-locations: classpath:mapper/*.xml # 配置加载mapperxml资源
  type-aliases-package: com.itheima.stock.pojo.entity # 批量给实体类取别名，方便xml中直接使用别名，避免冗余配置
  configuration:
    map-underscore-to-camel-case: true # 开启驼峰映射 sys_user-->SysUser
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl # 通过mybatis执行的sql以日志方式输出到终端
    cache-enabled: false # 禁止二级缓存 caffiencache
    local-cache-scope: statement # 一级缓存默认开启 session statement
# 配置分页插件
pagehelper:
  helper-dialect: mysql #配置分页的方言（数据库类型）
  reasonable: true # 开启合理查询：比如总页数100，当查询101页时，自动查询最后一页，当查询-1页，默认查询第一页